config/routes.rb
Rails.application.routes.draw do
  get 'example/index'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  devise_for :managers, controllers: { invitations: "managers/invitations", sessions: "managers/sessions", registrations: "managers/registrations" }


  # constraints for subdomains
  cnstrs = {subdomain: ENV["CRM_SUBDOMAIN"]}
  cnstrs = {} if ENV["LOCALHOST"] == "true"


  # CRM routes

  constraints cnstrs do
    #get "ng", to: "crm#ng"

    with_options defaults: {format: "html"} do
      get "skin-config", to: "crm#skin_config"
      root to: "dashboard#index", as: :crm_root

      resources :clients, :managers, :admins, :buildings, :building_complexes, :penthouses, :apartments, :apartment_houses do
        resources :assets, :comments
      end




      post "managers/invite"
    end
  end

  # Site routes

  root to: "application#site_home"

  match "*url", to: "application#render_not_found", via: [:get]

end

app/models/manager.rb
# == Schema Information
#
# Table name: users
#
#  created_at             :datetime         not null
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  id                     :integer          not null, primary key
#  invitation_accepted_at :datetime
#  invitation_created_at  :datetime
#  invitation_limit       :integer
#  invitation_sent_at     :datetime
#  invitation_token       :string
#  invited_by_id          :integer
#  invited_by_type        :string
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  profile_status         :string
#  provider               :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  tokens                 :text
#  type                   :string
#  uid                    :string           default(""), not null
#  updated_at             :datetime         not null
#

class Manager < User
  has_many :manager_client_links
  has_many :clients, through: :manager_client_links

  attr_accessible :first_name, :middle_name, :last_name, :phone, :country, :city
end

app/controllers/managers/confirmations_controller.rb
class Managers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/managers/invitations_controller.rb
class Managers::InvitationsController < Devise::InvitationsController
  respond_to :html, :json

  skip_before_filter :authenticate_inviter!

  def authenticate_inviter!
    current_user
    #authenticate_admin!(:force => true)
  end
end

app/controllers/managers/omniauth_callbacks_controller.rb
class Managers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/managers/passwords_controller.rb
class Managers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/managers/registrations_controller.rb
class Managers::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  prepend_before_filter :require_no_authentication
  #skip_before_filter :authenticate_scope!

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    #resource = current_manager
    super
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def authenticate_scope!
    self.resource = current_user
  end
end

app/controllers/managers/sessions_controller.rb
class Managers::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/managers/unlocks_controller.rb
class Managers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/managers_controller.rb
class ManagersController < ResourcesController
  #before_action :authorize_to_users!
  respond_to :json

  skip_before_filter :verify_authenticity_token



  def authorize_to_users!
    if cannot?(:manage, :users)
      render_unauthorized
    end
  end

  def invite

  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.require(:manager).permit(:email, :password, :first_name, :middle_name, :last_name, :phone, :country, :city, :street, :house_number, :apartment_number, :password_confirmation, :full_name, :avatar, :full_address, user_info_attributes: [:first_name, :last_name, :middle_name, :avatar, address_attributes: [:street, :house_number, :apartment_number, :index, :city, :country]] )
    end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/_clients_list.html.slim
.col-sm-8
  .ibox
    .ibox-content
      h2 Список Клієнтів
      input#filter.form-control.input-sm.m-b-xs placeholder=("Search in table") type="text" /
      br
      .table-responsive
        table.footable.table.table-stripped.toggle-arrow-tiny data-filter="#filter" data-page-size="10"
          thead
            tr
              th data-sort-ignore="true"
              th data-hide="phone" Ім’я Клієнта
              th data-hide="phone"  Група Клієнтів
              th data-hide="phone,tablet"  Статус Клієнта
              th data-sort-ignore="true"  Дія
            tbody
              - @resource.clients.each do |client|
                tr
                  td.client-avatar
                    - asset = client.user_info.assets.first || client.user_info.assets.build
                    = image_tag(asset.data.url)
                  td
                    a.client-link data-toggle="tab" href="#contact-1" = client.full_name
                  td class=client.group_text = client.group_list.first
                  td.client-status
                    span.label class=client.status_label = client.status_list.first
                  td
                    .btn-group
                      button.btn-white.btn.btn-xs Переглянути
                      button.btn-white.btn.btn-xs Редагувати
              tfoot
                tr
                  td colspan="6"
                    ul.pagination.pull-right

- content_for(:additional_scripts) do
  script
    |  $(document).ready(function() { $('.footable').footable(); });

app/views/managers/_page_heading.html.slim
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-8
    h2
      | Менеджери
    ol.breadcrumb
      li
        a = link_to root_url
          | Головна
      li.active
        strong
          a = link_to managers_path
            | Менеджери
  .col-lg-4
    .title-action[style="margin-right: 15px"]
      a = link_to new_building_path
        button.btn.btn-w-m.btn-warning[style="margin-right: 5px" type="button"]
          | Нова Нерухомість
      a = link_to new_client_path
        button.btn.btn-w-m.btn-primary type="button"
          | Новий Клієнт

app/views/managers/_search_managers.html.slim
.ibox-content.m-b-sm.border-bottom
  .row
    .col-sm-8
      .form-group
        label.control-label for="product_name" Ім’я менеджера
        input#search-manager.form-control.input-sm.m-b-xs placeholder=("Ім’я менеджера") type="text" /
    .col-sm-4
      .form-group
        label.control-label for="status"  Компанія
        select#manager-category.form-control name="status"
          option[data-filter="0" selected="selected"] Всі компанії
          - for company in @companies
            option data-filter=company.name value=company.name = company.name

app/views/managers/_toolbar.html.slim
.ibox-content.m-b-sm.border-bottom
  .row
    /= @resources.inspect
    a.btn.btn-warning href=new_resource_path
      = resource_class.human_model_name(:new)
    |&nbsp;
    = simple_form_for(:manager_invitation, url: manager_invitation_path, html: {style: "display: inline-block;"}, type: "post") do |form|
      = form.input :email
      button.btn.btn-warning.new-manager-invitation type="submit"  data-post-url=manager_invitation_path data-token="form_authenticity_token"
        | Запросити менеджера

app/views/managers/index.html.slim
= render "toolbar"
.row
  - @resources.each do |manager|
    .col-lg-4
      .contact-box
        a href=url_for(manager)
          .col-sm-4
            .text-center
              img.img-circle.m-t-xs.img-responsive alt="image" src="img/a2.jpg"
          .col-sm-8
            h3
              strong
                = manager.full_name
            address
              = manager.full_address
              br
              abbr title="Phone"  P:
              = manager.phone
          .clearfix

app/views/managers/show.html.slim
.row
  .col-sm-4
    .ibox.float-e-margins
      div
        .ibox-content.profile-content
          .row.m-b-lg
            .text-center
              h2
                = @resource.full_name
              .m-b-sm
                img.img-circle alt="image" src="/system/assets/data/000/000/001/original/chris.jpg?1436781569" style=("width: 62px")
          h5
            | Про менеджера
          p
            | Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitat.
          .user-button
            .row
              .col-md-6
                a href=edit_resource_path
                  button.btn.btn-outline.btn-primary type="button"  Редагувати дані