config/routes.rb
Rails.application.routes.draw do
  get 'example/index'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  devise_for :managers, controllers: { invitations: "managers/invitations", sessions: "managers/sessions", registrations: "managers/registrations" }


  # constraints for subdomains
  cnstrs = {subdomain: ENV["CRM_SUBDOMAIN"]}
  cnstrs = {} if ENV["LOCALHOST"] == "true"


  # CRM routes

  constraints cnstrs do
    #get "ng", to: "crm#ng"

    with_options defaults: {format: "html"} do
      get "skin-config", to: "crm#skin_config"
      root to: "dashboard#index", as: :crm_root

      resources :clients, :managers, :admins, :buildings, :building_complexes, :penthouses, :apartments, :apartment_houses do
        resources :assets, :comments
      end




      post "managers/invite"
    end
  end

  # Site routes

  root to: "application#site_home"

  match "*url", to: "application#render_not_found", via: [:get]

end

app/models/building.rb
# == Schema Information
#
# Table name: buildings
#
#  avatar_content_type :string
#  avatar_file_name    :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  created_at          :datetime         not null
#  full_description    :text
#  id                  :integer          not null, primary key
#  parent_id           :integer
#  parent_type         :string
#  price               :integer
#  price_currency      :string
#  published           :boolean
#  status              :string
#  type                :string
#  updated_at          :datetime         not null
#

class Building < ActiveRecord::Base
  attr_accessible *attribute_names
  has_one :address, as: :addressable, autosave: true
  has_many :assets, as: :assetable

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :assets
  attr_accessible :address, :address_attributes
  attr_accessible :assets, :assets_attributes

  has_many :comments, as: :commentable
  accepts_nested_attributes_for :comments
  attr_accessible :comments, :comments_attributes



  has_one :building_complex_link
  has_one :building_complex, through: :building_complex_link


  delegate_with_setter *Address.form_fields, to: :address, allow_nil: true
  delegate :full_address, to: :address, allow_nil: true

  has_many :user_views, class_name: "BuildingView"
  has_many :users_viewed, through: :user_views, source: :building

  has_attached_file :avatar
  attr_accessible :avatar
  do_not_validate_attachment_file_type :avatar

  #belongs_to :parent

  auto_build :address

  before_save :set_defaults
  def set_defaults
    if published.nil?
      published = false
    end

    return true
  end

  scope :published, -> { where(published: 't') }
  scope :available_for_manager, -> { published }
  scope :available_for_user, ->(user) {
    if user
      if user.instance_of?(Manager)
        return available_for_manager
      end
    else
      if user.instance_of?(Admin)
        return all
      end
    end
  }
end
# rails g model UserAttribute attributtable_type:string attributtable_id:integer attribute_name:string attribute_type:string required:boolean

app/models/building_view.rb
# == Schema Information
#
# Table name: building_views
#
#  building_id :integer
#  created_at  :datetime         not null
#  id          :integer          not null, primary key
#  starred     :boolean
#  updated_at  :datetime         not null
#  user_id     :integer
#

class BuildingView < ActiveRecord::Base
  belongs_to :user
  belongs_to :building
end

app/controllers/buildings_controller.rb
class BuildingsController < ResourcesController

  before_action :add_breadcrumbs
  before_action :new_breadcrumbs, only: :new
  before_action :show_breadcrumbs, only: :show
  before_action :edit_breadcrumbs, only: :edit

  def new_breadcrumbs
    @breadcrumbs << {name: resource_class.human_model_name(:new)}
  end

  def show_breadcrumbs
    @breadcrumbs << {name: @resource.to_s}
  end

  def edit_breadcrumbs
    @breadcrumbs << {name: @resource.to_s, url: url_for(@resource)}
    @breadcrumbs << {name: "Редагування"}
  end

  def resource_class
    Building
  end

  def index
    @resources ||= resource_class.all.includes(:address).order("id desc").limit(10)
  end

  def resource_params
    super
    #params.require(resource_name).permit(*Address.form_fields, :utf8, :_method, :authenticity_token, :building_complex, :format, :id, :latitude, :longitude, :avatar)
    #params.permit(:avatar)
    #params.require(resource_name).permit(:avatar)
  end

  def add_breadcrumbs
    @breadcrumbs << {name: t("breadcrumbs.buildings")}
    @breadcrumbs << {name: resource_class.human_model_name(multiple: true), url: url_for(resource_class)}
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper

end

app/views/buildings/_form.html.slim
= simple_form_for(@resource, html: {class: "wizard-form wizard-big", form_role: params[:action], :"data-resources-name" => resources_name, :"data-resource-name" => resource_name }) do |f|
  = render "_form_steps/main_step", form: f
  = render "_form_steps/tech_details_step", form: f
  = render "_form_steps/attachments_step", form: f
  = render "_form_steps/full_description_step", form: f

app/views/buildings/_index__table_header.html.slim
th[data-hide="all" data-sort-initial="descending"]
  |id
th[data-toggle="true"]
  |Назва
/th data-hide=""
  |Країна
/th[data-hide="phone"]
  |Місто
th[data-hide="phone"]
  |Площа
th[data-hide="phone"]
  |Ціна від, грн/м
  sup
    |2
th[data-hide="phone,tablet"]
  |К-сть кімнат

app/views/buildings/_index__table_rows.html.slim
- collection.each do |resource|
  tr
    td
      = resource.id
    td
      = resource.name
    /td
      = resource.country
    /td
      = resource.city
    td
      = "-"
      /= resource.square
    td
      = resource.price


    td.text-right
      .btn-group
        a.btn-white.btn.btn-xs href=url_for(resource)
          | View
        a.btn-white.btn.btn-xs href=url_for([:edit, resource])
          | Edit
        a.btn-white.btn.btn-xs href=url_for(resource) role="delete"
          | Delete

app/views/buildings/_index_links.html.slim
= link_to "Нова квартира", new_apartment_path

app/views/buildings/_index_table_columns.html.slim
= field building.full_address

= field building.price

= field building.price_currency

app/views/buildings/_show__main_info.html.slim
.col-lg-4
  .ibox
    .ibox-title
      .row
        .col-lg-9
          h5
            = @resource.to_s
        .col-lg-3
          a.btn.btn-warning href=url_for([:edit, @resource])
            |Редагувати
    /= "#{@resource.street }, #{@resource.address}"
    .ibox-content
      .avatar
        - if @resource.avatar.exists?
          = image_tag @resource.avatar.url
        - else
          .no-image
            .fa.fa-picture-o.fa-5x
            br
            .text
              |картинка відсутня
      = render "show__main_info_table_columns"

app/views/buildings/_show__main_info_table_columns.html.slim
table.show-item-main-info
  = vertical_table_field :status, resource: @resource
  = vertical_table_field :price, resource: @resource
  = vertical_table_field :square, resource: @resource

app/views/buildings/_show_details.html.slim
table.show-details
  thead
    th
      |Назва поля
    th
      |Вміст поля
  tbody
    - arr = [ *resource_class.details_attribute_names]
    - arr.each do |attr_name|
      tr
        td
          = raw @resource.class.human_attribute_name(attr_name)
        td
          = @resource.send(attr_name)

app/views/buildings/show.html.slim
.row
  = render "show__main_info"
  .col-lg-8
    .ibox.init-collapsed
      .ibox-title
        h5
          |Технічні характеристики
        .ibox-tools
          a.collapse-link
            i.fa.fa-chevron-up
          a.dropdown-toggle[data-toggle="dropdown" href="#"]
      .ibox-content
        = render "show_details"
    .ibox.init-collapsed
      .ibox-title
        h5
          |Атачменти
        .ibox-tools
          a.collapse-link
            i.fa.fa-chevron-up
          a.dropdown-toggle[data-toggle="dropdown" href="#"]
      .ibox-content
        .filemanager-toolbar
          .tool.delete
            .fa.fa-times.fa-1x
            |видалити
        div action=building_complex_assets_path(@resource) class="dropzone attachments-dropzone"
    .ibox.init-collapsed
      .ibox-title
        h5
          |Примітки
        .ibox-tools
          a.collapse-link
            i.fa.fa-chevron-up
          a.dropdown-toggle[data-toggle="dropdown" href="#"]
      .ibox-content.forum-post-container
        = render "show_comments"